// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.springframework.social.eventbrite.api;

import java.util.ArrayList;
import java.util.List;
import org.springframework.social.eventbrite.api.EventSearchParameters.SortBy;
import org.springframework.social.eventbrite.api.EventSearchParameters.WithInUnit;

public class EventSearchParametersBuilder extends EventSearchParametersBuilderBase<EventSearchParametersBuilder> {

	public static EventSearchParametersBuilder eventSearchParameters() {
		return new EventSearchParametersBuilder();
	}

	public EventSearchParametersBuilder() {
		super(new EventSearchParameters());
	}

	public EventSearchParameters build() {
		return getInstance();
	}
}

class EventSearchParametersBuilderBase<GeneratorT extends EventSearchParametersBuilderBase<GeneratorT>> {

	private EventSearchParameters instance;

	protected EventSearchParametersBuilderBase(EventSearchParameters aInstance) {
		instance = aInstance;
	}

	protected EventSearchParameters getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT keywords(List<String> aValue) {
		instance.setKeywords(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT keyword(String aValue) {
		if (instance.getKeywords() == null) {
			instance.setKeywords(new ArrayList<String>());
		}

		((ArrayList<String>) instance.getKeywords()).add(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT categories(List<String> aValue) {
		instance.setCategories(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT category(String aValue) {
		if (instance.getCategories() == null) {
			instance.setCategories(new ArrayList<String>());
		}

		((ArrayList<String>) instance.getCategories()).add(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT address(String aValue) {
		instance.setAddress(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT city(String aValue) {
		instance.setCity(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT region(String aValue) {
		instance.setRegion(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT postalCode(String aValue) {
		instance.setPostalCode(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT country(String aValue) {
		instance.setCountry(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIn(boolean aValue) {
		instance.setWithIn(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withInUnit(WithInUnit aValue) {
		instance.setWithInUnit(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT latitude(Double aValue) {
		instance.setLatitude(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT longitude(Double aValue) {
		instance.setLongitude(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT date(String aValue) {
		instance.setDate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT dateCreated(String aValue) {
		instance.setDateCreated(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT dateModified(String aValue) {
		instance.setDateModified(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIn(Boolean aValue) {
		instance.setWithIn(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT organizer(String aValue) {
		instance.setOrganizer(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT max(Integer aValue) {
		instance.setMax(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT countOnly(Boolean aValue) {
		instance.setCountOnly(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT sortBy(SortBy aValue) {
		instance.setSortBy(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT page(Integer aValue) {
		instance.setPage(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT trackingLink(String aValue) {
		instance.setTrackingLink(aValue);

		return (GeneratorT) this;
	}
}
